apiVersion: v1
kind: Secret
metadata:
  name: admission-tls
type: Opaque
data:
  webhook.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVU0c2RXB1YVpGdEFkTHpwQTljdk9mb3RTcXFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNUVXN4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TVRBM01UZ3lNRFUzTURsYUZ3MHlOREExCk1EY3lNRFUzTURsYU1FVXhDekFKQmdOVkJBWVRBazFMTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzJKclp2TGo2d0hvemEvYTdtUzdSTXlIbzZSMng2MHBFYXZyUGRtUjJkCllCd09jSUk0Z3hrVjNKczRnUjR0RzUyTkNRZngvK1hFNmYzTDJ4Y3dzbEJLUWFXVnREYmVvL3BzT1E1Y1hCNFUKcm5DT3VWcmw3Zk95YnVQWERaZUtuNkZMSEk0OW5rTTV2WDBKbFlmSEpGbXdvUlpzMSs5a0JySzJYSm5vUHpUOApNZ0RqRzJmMVhzQ2JIeVdIdko0aVB5bWZmMHEyZW9FZkcyb1JRM3hNcFpxVjZWNlhXamJLWm5yQWVxK0pLbEQzCm9nVzFwVEF4WXRsUUxRbVlqTmJZTE9Pb3hTYmJkQXNBS3M2TzVBMTFTRWxwekMwbnc4RGF5TkJmMjU0VDZ4TGkKY0E1VWdObForbU5GMFphdGNldk93WFRUS1VQMlEydDN5Ry9tV3ZhN0hJK3pBZ01CQUFHamREQnlNQjBHQTFVZApEZ1FXQkJUdkZOYnQ5bjhERjhoTldualBCKyt5Vnp3RzdqQWZCZ05WSFNNRUdEQVdnQlR2Rk5idDluOERGOGhOCldualBCKyt5Vnp3RzdqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01COEdBMVVkRVFRWU1CYUNGSFpoYkdsa1lYUmwKTG1SbFptRjFiSFF1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjBaeXE1U0lRNk0yUGhPMXRya1pZcAptVVh3am90UVZ4NTRLdjZFRjM4eTVHQnNQRlloS2ovRlBMTHN5RE5KTlE2WkdyL2ljbm44VmNaUmg2TXczUUM2CnhXSjFra093a2pobGNGMUs4MUdkNzFOT0djYU5WVE0rM0FDcEx3WEdUbUx4cUo0eWNyVzczMUZYT21pTW9WakkKWlNPakExdkZ5WW9wZXNaaFAycTdXc3ZiVVhFNVFoQ21meFB2NkhyNDZqOE5wNi9wYWcrb1BxdkNDWmgvTm9hLwoyMS82OWFtSzQ4aTNMVmJOcEJLVHAreGlYS0pCOWUzcUIvWkU5RGs5dXkxTzN2V1VUK3RWTjhLZ3ZONXdyMlpDClNIc2FPaEwraUtXeHBtYUJ1QUZFb2FUT2xlQTh2NUp5VGpOSkhqOWtSYTNjejJHZ1lQdUY5VFE3UUYxM2dTMFoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  webhook.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzJKclp2TGo2d0hvemEKL2E3bVM3Uk15SG82UjJ4NjBwRWF2clBkbVIyZFlCd09jSUk0Z3hrVjNKczRnUjR0RzUyTkNRZngvK1hFNmYzTAoyeGN3c2xCS1FhV1Z0RGJlby9wc09RNWNYQjRVcm5DT3VWcmw3Zk95YnVQWERaZUtuNkZMSEk0OW5rTTV2WDBKCmxZZkhKRm13b1JaczErOWtCcksyWEpub1B6VDhNZ0RqRzJmMVhzQ2JIeVdIdko0aVB5bWZmMHEyZW9FZkcyb1IKUTN4TXBacVY2VjZYV2piS1puckFlcStKS2xEM29nVzFwVEF4WXRsUUxRbVlqTmJZTE9Pb3hTYmJkQXNBS3M2Two1QTExU0VscHpDMG53OERheU5CZjI1NFQ2eExpY0E1VWdObForbU5GMFphdGNldk93WFRUS1VQMlEydDN5Ry9tCld2YTdISSt6QWdNQkFBRUNnZ0VBU3paZS9EZVhNUGZjWjR4NmpLTlQxcVN0TzZWRVdNN2JsYlNLNW9TVDR1ak4KalBUT0FIRzVpUHBucVlRL0pwY1JqaXZkZVFLV0tLSUo1d1FYWmtjcXVnNnpSY1o5SlorR0J1dmtUeVRHVXZuWQpoa1pwRHlvYkIyR2NlSzhuRk5sbkszR21GakZrUnRKRWNCR3JXQUpkZW41NW1RWHMxbHVocllVOUU5WU5sZGlKClY2eHVJNXJwMVBCNG44cnI2ZjVreFpPWGJkNVlibGFWVSthanJsZTN4bXkyM0FCa29VVUtSZG81eHZBNENHZ2wKMW4wV3RUcFB6R0NraWFPSjFmRytKYkV2d2dqQTZXK0xKOEVUdEFqVjIxMzNLdXM1eEFMRnNWWGFLR2gxeDF5eQpVdmZidkljdXFXNE1semt2UklWT2lPeFgyN2VlSUZJcWE0YmJOaEQ1V1FLQmdRRGlWemFYSm43eXkrRm1Nd3haClYwM1dIaGYwVFVnWWlXcHBvRjZPdy92WUlpQld1TUFzNXl1SmpCMThFWXBVZVNQYVJLa3YvdkpJM3NmRm1BaEUKMkwxQWhqT1BvbE9xUyttSTQwUXBQbDRMbVR0TnlwT0RZUFpTWnRtdlJqMEQ1UHhmYzZtTWgram9ady81bmZCeAo1TEV1V3pjSkFaVmVqdWdkbG5TMm94d2xwd0tCZ1FET0JTQ1RzZ29SVEtIUG96WTFMTWExNjFXak8ydnNWRVpOCjU3M3RnOXp5ZGdOak1NN0RaMDVTSWtNZEV0c2N2Tm9vVUVESzlrWHlPYjg5MU5TUjZIaU9xTVJEcG9TeGVRVmIKRHBET3h0KzBOTUFKR21WM045ZWtKS2twK1ZVYzQzMGxiUk53MTB6czdNVDdLc3AwMFc3NGJnL0I0bjQ0dXI3NgpJeWp5VlJmZkZRS0JnQVAyR010K2JmeGIyeDhKeDY2TW01MGl1N0tYNDZvaVJZMkJ0QVgxb2lPL1BTZW5aaDJqCkVoei9LY2p4R2FXdTFSVE4zTlF0TnhwVlk5T3VmSDZQK0lmM2tWRnpPdG1oS0g0djFCS1F0OTZtR09hY3BBWkoKblNZR0RNdEhoR3ZjQnhxNGtJQVlKTmhrYldBbUJuNUh6VjROVktKQXQ5ZUcwc01wemZNZ1dhN0RBb0dCQUtUKwpTamErMFgxRlNCbklkbk5qcHNpdTdtaktBQWJHLzM4STUzeStyRWFwNk5DWm1CMjZNR2xxOHlEbnB2OSs1NkI5CmxVWjJzVkhxbVpSbFROQ0Z3M2ROQmRIQUhHa2RxUUpoeWVzd0xweGQycVh2cys4a2s5anJXMmM0UGNmakVLalcKa0VsQXhHVEN3b2I4b0NPcVR4czYyZmZHOHB0d1E5NkVKaGpkdVQ1NUFvR0FSQ0tMTW9hcHpKT20wZHZtWnlNKwp5QW9hbmRCMlFiSVlRYXVESmlBeGptV21sYlNPcEh5OEZSYTRTV01sVTVuR0RkcHpJMWZIeU5hWjFreCtROVJwCi9YdnRqWXduUHQrY0dzeENUd2EwTDZBMGNLU2UzdkNqNXM1bkZDQTN5VTR5aExrd2xhWGNtMnBZTGZBRkJnL2cKZ2NVQnFxRnNLYzFYdzhCUEUrWllCR2s9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  labels:
    app: validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
      - name: webhook
        image: validate:v1
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        imagePullPolicy: IfNotPresent
      volumes:
      - name: certs-volume
        secret:
          secretName: admission-tls
---
apiVersion: v1
kind: Service
metadata:
  name: validate
spec:
  selector:
    app: validate
  ports:
  - port: 443
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating.admission.webhook
webhooks:
  - name: validating.admission.webhook
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["production", "prod"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: validate
        namespace: default
        path: /validate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVU0c2RXB1YVpGdEFkTHpwQTljdk9mb3RTcXFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNUVXN4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TVRBM01UZ3lNRFUzTURsYUZ3MHlOREExCk1EY3lNRFUzTURsYU1FVXhDekFKQmdOVkJBWVRBazFMTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzJKclp2TGo2d0hvemEvYTdtUzdSTXlIbzZSMng2MHBFYXZyUGRtUjJkCllCd09jSUk0Z3hrVjNKczRnUjR0RzUyTkNRZngvK1hFNmYzTDJ4Y3dzbEJLUWFXVnREYmVvL3BzT1E1Y1hCNFUKcm5DT3VWcmw3Zk95YnVQWERaZUtuNkZMSEk0OW5rTTV2WDBKbFlmSEpGbXdvUlpzMSs5a0JySzJYSm5vUHpUOApNZ0RqRzJmMVhzQ2JIeVdIdko0aVB5bWZmMHEyZW9FZkcyb1JRM3hNcFpxVjZWNlhXamJLWm5yQWVxK0pLbEQzCm9nVzFwVEF4WXRsUUxRbVlqTmJZTE9Pb3hTYmJkQXNBS3M2TzVBMTFTRWxwekMwbnc4RGF5TkJmMjU0VDZ4TGkKY0E1VWdObForbU5GMFphdGNldk93WFRUS1VQMlEydDN5Ry9tV3ZhN0hJK3pBZ01CQUFHamREQnlNQjBHQTFVZApEZ1FXQkJUdkZOYnQ5bjhERjhoTldualBCKyt5Vnp3RzdqQWZCZ05WSFNNRUdEQVdnQlR2Rk5idDluOERGOGhOCldualBCKyt5Vnp3RzdqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01COEdBMVVkRVFRWU1CYUNGSFpoYkdsa1lYUmwKTG1SbFptRjFiSFF1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjBaeXE1U0lRNk0yUGhPMXRya1pZcAptVVh3am90UVZ4NTRLdjZFRjM4eTVHQnNQRlloS2ovRlBMTHN5RE5KTlE2WkdyL2ljbm44VmNaUmg2TXczUUM2CnhXSjFra093a2pobGNGMUs4MUdkNzFOT0djYU5WVE0rM0FDcEx3WEdUbUx4cUo0eWNyVzczMUZYT21pTW9WakkKWlNPakExdkZ5WW9wZXNaaFAycTdXc3ZiVVhFNVFoQ21meFB2NkhyNDZqOE5wNi9wYWcrb1BxdkNDWmgvTm9hLwoyMS82OWFtSzQ4aTNMVmJOcEJLVHAreGlYS0pCOWUzcUIvWkU5RGs5dXkxTzN2V1VUK3RWTjhLZ3ZONXdyMlpDClNIc2FPaEwraUtXeHBtYUJ1QUZFb2FUT2xlQTh2NUp5VGpOSkhqOWtSYTNjejJHZ1lQdUY5VFE3UUYxM2dTMFoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
